services:
  airlines-hub:
    build:
      context: ./AirlinesHub
    ports:
      - "8081:8080"

  exchange-service:
    build:
      context: ./ExchangeService
    ports:
      - "8082:8080"

  fidelity:
    build:
      context: ./Fidelity
    ports:
      - "8083:8080"

  travel-service:
    build:
      context: ./TravelService
    ports:
      - "8084:8080"
